name: Release
on:
  workflow_run:
    branches:
      - master
    workflows:
      - Build branch
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn install
      - name: Release
        run: yarn release
